version: "3.8"

volumes:
  pgdata:

networks:
  gn-cloud-network:
    driver: bridge

services:
  geonetwork:
    image: geonetwork:4.0.6
    user: root # Only for DEV env
    environment:
      DATA_DIR: /catalogue-data

      JAVA_OPTIONS: >
        -Dorg.eclipse.jetty.annotations.AnnotationParser.LEVEL=OFF
        -Djava.security.egd=file:/dev/./urandom -Djava.awt.headless=true
        -Xms512M -Xss512M -Xmx2G -XX:+UseConcMarkSweepGC
        -Dgeonetwork.resources.dir=/catalogue-data/resources
        -Dgeonetwork.data.dir=/catalogue-data
        -Dgeonetwork.codeList.dir=/catalogue-data/codeList
        -Dgeonetwork.schema.dir=/var/lib/jetty/webapps/geonetwork/WEB-INF/data/config/schema_plugins
      ES_HOST: elasticsearch
      ES_PROTOCOL: http
      ES_PORT: 9200

      KB_URL: http://kibana:5601

      GEONETWORK_DB_TYPE: postgres
      GEONETWORK_DB_HOST: database
      GEONETWORK_DB_PORT: 5432
      GEONETWORK_DB_NAME: "${MDDB_DBNAME}"
      GEONETWORK_DB_USERNAME: "${MDDB_USERNAME}"
      GEONETWORK_DB_PASSWORD: "${MDDB_PASSWORD}"
    volumes:
      - ./data/catalogue-data:/catalogue-data
    networks:
      - gn-cloud-network
    ports:
      - "8080:8080"
    depends_on:
      - kibana
      - elasticsearch
      - database

  elasticsearch:
    image: elasticsearch:7.9.2
    user: root # Only for DEV env
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    environment:
      ES_JAVA_OPTS: "-Xms1G -Xmx1G"
      discovery.type: single-node
    volumes:
      - ./data/esdata:/usr/share/elasticsearch/data
    networks:
      - gn-cloud-network
    ports:
      - "9200:9200"

  kibana:
    image: kibana:7.9.2
    environment:
      SERVER_NAME: 'kibana'
      ELASTICSEARCH_URL: http://elasticsearch:9200/
      SERVER_BASEPATH: /geonetwork/dashboards
      SERVER_REWRITEBASEPATH: 'false'
      KIBANA_INDEX: .dashboards
      XPACK_MONITORING_UI_CONTAINER_ELASTICSEARCH_ENABLED: 'true'
    networks:
      - gn-cloud-network
    depends_on:
      - elasticsearch

  database:
    image: mdillon/postgis
    environment:
      POSTGRES_USER: "${MDDB_DBNAME}"
      POSTGRES_PASSWORD: "${MDDB_USERNAME}"
      POSTGRES_DB: "${MDDB_PASSWORD}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - gn-cloud-network
    ports:
      - "5432:5432"
