spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/geonetwork
    username: geonetwork
    password: geonetwork

gn:
  baseurl: http://localhost:9901
  language:
    default: eng
  legacy.url: http://localhost:8080/geonetwork
  index:
    url: http://localhost:9200
    records: gn-records
    username:
    password: